version: '3'

services:
  neuroservice_app:
    build:
      context: ../violence-neuroservice
      dockerfile: ./Dockerfile
    ports:
      - "8005:8005"
    networks:
      - network
    env_file:
      - ../violence-neuroservice/.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
      placement:
        constraints:
          - node.role == manager

networks:
  network:

volumes:
  static: