version: '3.7'

services:
    neuroservice_app:
        build:
            context: ../violence-neuroservice
            dockerfile: ./Dockerfile
        restart: unless-stopped
        expose:
            - "8005"
        env_file:
          - ../violence-neuroservice/.env
        deploy:
            replicas: 3


    nginx-balancer:
        image: nginx
        restart: unless-stopped
        volumes:
            - ../violence-neuroservice/nginx-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - neuroservice_app
        ports:
            - "8080:8005"