version: '3'

services:
  neuroservice_app:
    build:
      context: ../violence-neuroservice
      dockerfile: ./Dockerfile
    ports:
      - "8005:8005"
    networks:
      - network
    env_file:
      - ../violence-neuroservice/.env
    deploy:
      placement:
        constraints:
          - node.role == manager

  video-capture-service:
    build:
      context: ../video-capture-service
    env_file:
      - ../video-capture-service/.env
    restart: unless-stopped
    networks:
      - network
    ports:
      - "8001:8001"

networks:
  network:

volumes:
  static: