version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_KAFKA_HOST}
      KAFKA_CREATE_TOPICS: "prediction:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_ENDPOINT: ${API_URL}
    ports:
      - ${FRONTEND_PORT}:3000
    restart: always

  video-capture-service:
    depends_on:
      - kafka
      - zookeeper
    build:
      context: ./video-capture-service
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - network
    ports:
      - 8001:8001

  video-stream-service:
    depends_on:
      - video-capture-service
    build:
      context: ./video-stream-service
    env_file:
      - ./.env
    volumes:
      - static:/streams
    restart: always
    networks:
      - network
    ports:
      - ${STREAM_SERVICE_PORT}:8000

  backend:
    depends_on:
      - kafka
      - zookeeper
    build:
      context: ./backend
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - network
    ports:
      - ${BACKEND_PORT}:8006


networks:
  network:

volumes:
  static: